import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

// This will generate: <meta name="viewport" content="width=device-width, initial-scale=1" />
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  // Add additional fields if necessary:
  // maximumScale: 1,
  // userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        spaceGrotesk.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="h-full">
        <div className="flex min-h-full flex-col overflow-hidden">
          <main className="flex-auto"> {children}</main>
        </div>
      </body>
    </html>
  );
}
